default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 6989
  host: localhost


development:
  <<: *default
  database: sample_app_development #　DBの名前。「sample」の部分をアプリの名前に変更すると分かりやい

test:
  <<: *default
  database: sample_app_test #　DBの名前。「sample」の部分をアプリの名前に変更すると分かりやい

production:
  <<: *default
  database: sample_production
  username: sample_app
  password: <%= ENV['SAMPLE_DATABASE_PASSWORD'] %>